@admin-jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjgyODQzNTN9.m5JROmskx2wfvjaNXJ8ZV_iuLfQbV-AP1SsCRwRdJpk
@jwt1 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgyODQzNzN9.ygIqGs2MUBJd3Sih-RAsGHY4R8m5eKHem4CFDESOWew

### PRODUCTS INDEX

GET http://localhost:3000/products.json
Authorization: Bearer {{jwt1}}

### PRODUCTS SHOW

GET http://localhost:3000/products/3.json
Authorization: Bearer {{jwt1}}

### PRODUCTS CREATE

POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{jwt1}}

{
  "name": "Weed Trimmer",
  "price": 64,
  "description": "Wack those weeds with a weed trimmer.",
  "supplier_id": 1
}

### PRODUCTS UPDATE

PATCH http://localhost:3000/products/12.json
Content-Type: application/json
Authorization: Bearer {{jwt1}}

 {
  "name": "Nuclear Lawnmower",
  "price": 59,
  "description": "A safer fuel alternative to lawnmowing.",
  "supplier_id": 2
 }

### PRODUCTS DESTROY

 DELETE http://localhost:3000/products/6
Authorization: Bearer {{admin-jwt}}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Mark Rubin",
  "email": "mark@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### USERS UPDATE


### SESSIONS CREATE [LOG IN]

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt1}}

### ORDERS SHOW

GET http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt1}}

### ORDERS CREATE

POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwt1}}

{
  "product_id": 2,
  "quantity": 3
}