### PRODUCTS INDEX

GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjgxOTM3NDh9.3BWzxYTenVSH_9dTSejB8NlTf8QcHsnDZKNiyGFUgbE

### PRODUCTS SHOW

GET http://localhost:3000/products/3.json

### PRODUCTS CREATE

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Weed Trimmer",
  "price": 64,
  "description": "Wack those weeds with a weed trimmer.",
  "supplier_id": 1
}

### PRODUCTS UPDATE

PATCH http://localhost:3000/products/12.json
Content-Type: application/json

 {
  "name": "Nuclear Lawnmower",
  "price": 59,
  "description": "A safer fuel alternative to lawnmowing.",
  "supplier_id": 2
 }

### PRODUCTS DESTROY

 DELETE http://localhost:3000/products/6

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test2.com",
  "password": "password",
  "password_confirmation": "password"
}

### SESSIONS CREATE [LOG IN]

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test2.com",
  "password": "password"
}